---
# ConfigMap con el script Python del webhook receiver
apiVersion: v1
kind: ConfigMap
metadata:
  name: webhook-receiver-script
  namespace: monitoring-8
data:
  webhook-receiver.py: |
    #!/usr/bin/env python3
    from http.server import HTTPServer, BaseHTTPRequestHandler
    import json
    from datetime import datetime
    
    class WebhookHandler(BaseHTTPRequestHandler):
        def do_POST(self):
            content_length = int(self.headers['Content-Length'])
            post_data = self.rfile.read(content_length)
            
            try:
                alert_data = json.loads(post_data.decode('utf-8'))
                
                print("\n" + "="*80)
                print(f"🚨 ALERTA RECIBIDA - {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
                print("="*80)
                
                if 'alerts' in alert_data:
                    for alert in alert_data['alerts']:
                        status = alert.get('status', 'unknown')
                        labels = alert.get('labels', {})
                        annotations = alert.get('annotations', {})
                        
                        severity = labels.get('severity', 'unknown')
                        alertname = labels.get('alertname', 'unknown')
                        
                        # Emoji según severidad
                        emoji = "🔴" if severity == "critical" else "⚠️" if severity == "warning" else "ℹ️"
                        
                        print(f"\n{emoji} Alerta: {alertname}")
                        print(f"   Estado: {status}")
                        print(f"   Severidad: {severity}")
                        print(f"   Categoría: {labels.get('category', 'N/A')}")
                        
                        if 'summary' in annotations:
                            print(f"   Resumen: {annotations['summary']}")
                        
                        if 'description' in annotations:
                            print(f"   Descripción: {annotations['description']}")
                        
                        if 'action' in annotations:
                            print(f"   Acción recomendada: {annotations['action']}")
                        
                        print(f"   Labels: {json.dumps(labels, indent=2)}")
                
                print("="*80 + "\n")
                
                # Responder con 200 OK
                self.send_response(200)
                self.send_header('Content-type', 'application/json')
                self.end_headers()
                self.wfile.write(json.dumps({"status": "success"}).encode())
                
            except Exception as e:
                print(f"❌ Error procesando alerta: {e}")
                self.send_response(500)
                self.end_headers()
        
        def do_GET(self):
            # Health check
            self.send_response(200)
            self.send_header('Content-type', 'text/plain')
            self.end_headers()
            self.wfile.write(b"Webhook Receiver OK - Esperando alertas...\n")
        
        def log_message(self, format, *args):
            # Silenciar logs de acceso HTTP
            pass
    
    if __name__ == '__main__':
        server = HTTPServer(('0.0.0.0', 8080), WebhookHandler)
        print("🎯 Webhook Receiver iniciado en puerto 8080")
        print("📡 Esperando alertas de Alertmanager...")
        print("💡 Tip: Usa 'kubectl logs -f deployment/webhook-receiver -n monitoring-8' para ver alertas en tiempo real")
        server.serve_forever()

---
# Deployment del webhook receiver con Python
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook-receiver
  namespace: monitoring-8
  labels:
    app: webhook-receiver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webhook-receiver
  template:
    metadata:
      labels:
        app: webhook-receiver
    spec:
      containers:
      - name: webhook-receiver
        image: python:3.11-alpine
        command:
        - python3
        - /app/webhook-receiver.py
        ports:
        - containerPort: 8080
          name: http
        volumeMounts:
        - name: script
          mountPath: /app
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "200m"
      volumes:
      - name: script
        configMap:
          name: webhook-receiver-script
          defaultMode: 0755

---
# Service para exponer el webhook receiver
apiVersion: v1
kind: Service
metadata:
  name: webhook-receiver
  namespace: monitoring-8
  labels:
    app: webhook-receiver
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: webhook-receiver
