apiVersion: v1
kind: Pod
metadata:
  name: stress-cpu-test
  namespace: la-huella-8
spec:
  containers:
    - name: stress-cpu-test
      image: polinux/stress
      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: "1"       # Puedes dejarlo en 1 o subirlo a 2. Con 1 funciona igual.
          memory: "256Mi"
      command: ["stress"]
      args: ["--cpu", "2", "--timeout", "420s"]
  restartPolicy: Never