apiVersion: v1
kind: Pod
metadata:
  name: stress-cpu-test
  namespace: la-huella-8
spec:
  containers:
    - name: stress-cpu-test
      image: polinux/stress
      resources:
        requests:
          cpu: "500m"
          memory: "128Mi"
        limits:
          cpu: "2"
          memory: "256Mi"
      command: ["stress"]
      args: ["--cpu", "4", "--timeout", "420s"]
  restartPolicy: Never